package com.seguridad.constant;

/**
 * Clase constante que contiene los DMLs Y DDLs para las consultas nativas
 */
public class SQLConstant {

	/** SQL para obtener los datos personales del usuario con base a sus credenciales*/
	public static final String GET_USER_AUTH =
		"SELECT "
			  + "U.ID_USUARIO,"
			  + "CONCAT(P.PRIMER_NOMBRE,' ',P.SEGUNDO_NOMBRE,' ',P.PRIMER_APELLIDO,' ',P.SEGUNDO_APELLIDO)AS NOMBRE,"
			  + "STRING_AGG(DISTINCT RO.NOMBRE, ', ')AS ROLES,"
			  + "U.PRIMER_INGRESO,"
			  + "U.CLAVE,"
			  + "STRING_AGG(DISTINCT RO.ID_ROL\\:\\:VARCHAR, ',')AS ID_ROLES "
		+ "FROM PERSONAS P "
		+ "JOIN USUARIOS U ON(U.ID_USUARIO=P.ID_PERSONA)"
		+ "JOIN USUARIOS_ROLES_EMPRESAS UR ON(UR.ID_USUARIO=U.ID_USUARIO)"
		+ "JOIN ROLES RO ON(RO.ID_ROL=UR.ID_ROL)"
		+ "WHERE U.NOMBRE_USUARIO=? "
		+ "AND U.ID_ESTADO='" + Estado.ACTIVO
		+ "'AND UR.ID_ESTADO='" + Estado.ACTIVO
		+ "'AND RO.ID_ESTADO='" + Estado.ACTIVO
		+ "'GROUP BY 1,2";

	/** SQL para obtener los datos personales del usuario con base a sus credenciales*/
	public static final String GET_USER_AUTH_MOBILE =
		"SELECT "
			  + "U.ID_USUARIO,"
			  + "CONCAT(P.PRIMER_NOMBRE,' ',P.SEGUNDO_NOMBRE,' ',P.PRIMER_APELLIDO,' ',P.SEGUNDO_APELLIDO)AS NOMBRE,"
			  + "U.PRIMER_INGRESO, U.CLAVE, U.NUMERO_TELEFONO, "
			  + "STRING_AGG(DISTINCT RO.NOMBRE, ', ') AS ROLES, STRING_AGG(DISTINCT RO.ID_ROL\\:\\:VARCHAR, ',')AS ID_ROLES "
		+ "FROM PERSONAS P "
		+ "JOIN USUARIOS U ON(U.ID_USUARIO=P.ID_PERSONA) "
		+ " LEFT JOIN USUARIOS_ROLES_EMPRESAS UR ON(UR.ID_USUARIO=U.ID_USUARIO) LEFT JOIN ROLES RO ON(RO.ID_ROL=UR.ID_ROL) "
		+ "WHERE U.numero_telefono=? "
		+ "AND U.ID_ESTADO='" + Estado.ACTIVO + "' GROUP BY 1,2";

	/** SQL para obtener los items del menu parametrizados en el sistema*/
	public static final String GET_ITEMS_MENU =
			"SELECT "
			  + "REP.ID_RECURSO AS ID_ITEM_PADRE,"
			  + "REP.NOMBRE AS NOMBRE_ITEM_PADRE,"
			  + "REP.DESCRIPCION AS DESC_ITEM_PADRE,"
			  + "RE.ID_RECURSO AS ID_ITEM,"
			  + "RE.NOMBRE AS NOMBRE_ITEM,"
			  + "RE.DESCRIPCION AS DESC_ITEM,"
			  + "RE.URL AS URL_ITEM,"
			  + "ACC.ID_ESTADO AS ESTA_ACCION, "
			  + "ACC.ID_ACCION AS ID_ACCION,"
			  + "ACC.NOMBRE AS NOMBRE_ACCION, "
			  + "RE.ICONO AS ICONO_HIJO, "
			  + "REP.ICONO AS ICONO_PADRE "
		+ "FROM ROLES_RECURSOS_ACCIONES RRA "
		+ "JOIN ROLES RO ON(RO.ID_ROL=RRA.ID_ROL)"
		+ "JOIN RECURSOS RE ON(RE.ID_RECURSO=RRA.ID_RECURSO)"
		+ "JOIN ACCIONES ACC ON(ACC.ID_ACCION=RRA.ID_ACCION)"
		+ "JOIN RECURSOS REP ON(REP.ID_RECURSO=RE.ID_RECURSO_PADRE)"
		+ "WHERE RO.ID_ROL IN(SELECT URE.ID_ROL FROM USUARIOS_ROLES_EMPRESAS URE WHERE URE.ID_USUARIO=? AND URE.ID_ESTADO='" + Estado.ACTIVO + "')"
		+ "AND RE.ID_APLICACION=? "
		+ "AND RO.ID_ESTADO='" + Estado.ACTIVO
		+ "'AND RRA.ID_ESTADO='" + Estado.ACTIVO
		+ "'AND RE.ID_ESTADO='"+ Estado.ACTIVO
		+ "'AND REP.ID_ESTADO='"+ Estado.ACTIVO
		+ "'ORDER BY RE.NOMBRE ASC,REP.NOMBRE ASC";

	/** SQL para obtener los modulos del menu*/
	public static final String GET_MODULOS =
		"SELECT "
			+ "R.ID_RECURSO AS A,"
			+ "R.NOMBRE AS B,"
			+ "R.DESCRIPCION AS C,"
			+ "R.ICONO AS D,"
			+ "R.ID_RECURSO_PADRE AS E,"
			+ "EXISTS(SELECT * FROM RECURSOS RE WHERE RE.ID_RECURSO_PADRE=R.ID_RECURSO AND RE.ID_RECURSO IN(SELECT RRE.ID_RECURSO FROM ROLES_RECURSOS_ACCIONES RRE WHERE RRE.ID_ROL IN(SELECT URE.ID_ROL FROM USUARIOS_ROLES_EMPRESAS URE WHERE URE.ID_USUARIO=? AND URE.ID_ESTADO='" + Estado.ACTIVO + "')))AS F "
		+ "FROM RECURSOS R "
		+ "WHERE R.ID_ESTADO='" + Estado.ACTIVO + "'"
		+ "AND (R.ID_RECURSO_PADRE IS NULL OR R.URL IS NULL)"
		+ "AND R.ID_APLICACION=? "
		+ "ORDER BY R.NOMBRE";

	public static final String SELECT_MAIL_ID_PERSON = "select P.correo_electronico from personas p where p.id_persona=:id";
	
	public static final String GET_PROGRAMACION_VENDEDOR = "SELECT  HVD.OFICINA, HVD.PUNTO_VENTA, HORA_FINAL " 
			+ "FROM  HORARIOS_VENDEDORES HV JOIN HORARIOS_VENDEDORES_DETALLES HVD ON (HV.ID_HORARIO_VENDEDOR = HVD.ID_HORARIO_VENDEDOR) JOIN HORARIOS HO ON(HO.CODIGO_HORA=HVD.HORA) "
			+ "WHERE HV.ID_VENDEDOR =:idUsuario AND TO_CHAR(HVD.DIA,'YYYY-MM-DD') = TO_CHAR(CURRENT_DATE,'YYYY-MM-DD') " 
			+ "AND HO.HORA_INICIAL <= to_char(timezone('GMT 5', CURRENT_TIMESTAMP), 'HH24:MI:SS') AND to_char(timezone('GMT 5', CURRENT_TIMESTAMP), 'HH24:MI:SS') <= HO.HORA_FINAL "
			+ "AND HV.ID_ESTADO='" + Estado.ACTIVO
			+ "'AND HVD.ID_ESTADO='" + Estado.ACTIVO
			+ "'AND HO.ID_ESTADO='"+ Estado.ACTIVO +"'";
	
	public static final String GET_ROL_PROGRAMACION = "SELECT EXISTS(SELECT 1 FROM PERSONAS P JOIN USUARIOS U ON(U.ID_USUARIO=P.ID_PERSONA)JOIN USUARIOS_ROLES_EMPRESAS UR ON(UR.ID_USUARIO=U.ID_USUARIO)" 
			+ " JOIN ROLES RO ON(RO.ID_ROL=UR.ID_ROL) WHERE U.ID_USUARIO =:idUsuario AND RO.ID_PROGRAMACION = '"+ Estado.ACTIVO +"')";
}
